export enum UserType {
    ADMIN = 'ADMIN',
    FREELANCE = 'FREELANCE',
    CUSTOMER = 'CUSTOMER',
    COMPANY_OWNER = 'COMPANY_OWNER',
    COMPANY_PM = 'COMPANY_PM',
    COMPANY_TEAM_MEMBER = 'COMPANY_TEAM_MEMBER',
    COMPANY_SALESREP = 'COMPANY_SALESREP',
    COMPANY_CLOSER = 'COMPANY_CLOSER',
}